feat: Added step to detect wrongly named tests (#5)
* feat: Added step to detect wrongly named tests

* fix: Only first line

* fix: With sed

* fix: With matching

* fix: Print grep version

* fix: Exit code 0 in case of no matches

* fix: Removed write to output

* fix: Additional ' character

* fix: Print value

* fix: Attempt to use an integer and not a string

* fix: Different attempt to check result

* feat: Attempt to fail the matching condition

* fix: Debug

* fix: Wrong output name

* fix: Naming pattern

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -10,8 +10,31 @@ on:
       - "cmd/**"
 
 jobs:
+  check-test-names:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Detect tests not matching naming pattern
+        id: matching
+        # https://unix.stackexchange.com/questions/330660/preventing-grep-from-causing-premature-termination-of-bash-e-script
+        run: |
+          grep -rh 'func Test' --include *_test.go > all_tests.txt
+          sed -i 's/func //g' all_tests.txt
+          grep -vE '^Test(Unit|IT)_' all_tests.txt > not_matching.txt || [[ $? == 1 ]]
+          FAILURES=$(wc -l < not_matching.txt)
+          if [[ ${FAILURES} -ne 0 ]]; then
+            echo 'failed=true' >> $GITHUB_OUTPUT
+          fi
+      - name: Fail if some do not match
+        if: ${{ steps.matching.outputs.failed == 'true' }}
+        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#example-setting-an-error-message
+        run: |
+          echo "::error ::Detected at least one test not matching the naming convention!"
+          exit 1
+
   tests:
     runs-on: ubuntu-latest
+    needs: [check-test-names]
     steps:
       - uses: actions/checkout@v4
       - name: Setup Go
@@ -29,6 +52,7 @@ jobs:
 
   it-tests:
     runs-on: ubuntu-latest
+    needs: [check-test-names]
     services:
       postgres:
         image: postgres:15
