feat: Added an e2e tests step (#7)
* feat: Added a e2e tests step

* feat: Do not start the user-service as a service container but as a docker image

* fix: Indentation

* fix: Removed ports

* fix: Wrong image name and temporarily broke dependency on tests

* fix: Hardcoded tag for now

* fix: Run in detached mode and stop the container

* feat: All in one step

* feat: Saved the results of the test and used 127.0.0.1

* fix: Expose the port when running docker and reverted back to localhost

* fix: Multi-line command syntax error

* feat: Attempt to verify the results of the test

* fix: Structure and syntax error

* fix: Correct regexp

* fix: Attempt to escape string

* fix: Wrong syntax

* fix: Syntax error

* fix: Invert match for the regular expression

* feat: Try to use a service container again

* fix: Missing credentials

* fix: Attempt to use localhost directly

* fix: Attempt to use the postgres credentials

* feat: Do not use a service but pull the docker image

* feat: New attempt with service container

* Revert "feat: New attempt with service container"

This reverts commit b8ec5c8c692a62ee2f5f13006ceb44124bb3953e.

* techdebt: Voluntarily break the tests and the success response

* feat: E2E tests are dependent on image build

* techdebt: Also fail when explicitly setting status code

* fix: Restored correct response envelope

* techdebt: Change the return code of list endpoint

* fix: Restored correct status code

* fix: Restored build and push of docker image after tests are green

diff --git a/.github/workflows/build-and-push.yml b/.github/workflows/build-and-push.yml
--- a/.github/workflows/build-and-push.yml
+++ b/.github/workflows/build-and-push.yml
@@ -165,3 +165,100 @@ jobs:
           build-args: GIT_COMMIT_HASH=${{ needs.extract-service-tag.outputs.version }}
           push: true
           tags: totocorpsoftwareinc/user-service:${{ needs.extract-service-tag.outputs.version }}
+
+  e2e-tests:
+    runs-on: ubuntu-latest
+    needs: [build-and-push-docker-image, extract-service-tag]
+    services:
+      postgres:
+        image: postgres:15
+        env:
+          POSTGRES_USER: postgres
+          POSTGRES_PASSWORD: postgres
+          POSTGRES_DB: postgres
+        ports:
+          - 5432:5432
+        options: >-
+          --health-cmd pg_isready
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
+    steps:
+      - uses: actions/checkout@v4
+      - name: Setup Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: "1.23.2"
+      - name: Install migrate tool
+        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
+      - name: Setup users database
+        run: |
+          psql \
+            postgresql://postgres@localhost \
+            -v admin_password=$ADMIN_PASSWORD \
+            -v manager_password=$MANAGER_PASSWORD \
+            -v user_password=$USER_PASSWORD \
+            -f users/db_user_create.sql
+          psql \
+            postgresql://postgres@localhost \
+            -f users/db_create.sql
+        working-directory: ./database
+        env:
+          PGPASSWORD: postgres
+          ADMIN_PASSWORD: admin_password
+          MANAGER_PASSWORD: manager_password
+          USER_PASSWORD: user_password
+      - name: Migrate schema up
+        run: |
+          migrate \
+            -path users/migrations \
+            -database postgresql://user_service_admin@localhost/db_user_service?sslmode=disable \
+            up
+        working-directory: ./database
+        env:
+          PGPASSWORD: admin_password
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - name: Pull latest docker image
+        run: |
+          docker pull totocorpsoftwareinc/user-service:${{ needs.extract-service-tag.outputs.version }}
+      - name: Test docker image
+        # https://superuser.com/questions/272265/getting-curl-to-output-http-status-code
+        # https://stackoverflow.com/questions/24254064/how-to-get-curl-to-output-only-http-response-body-json-and-no-other-headers-et
+        # https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/about-service-containers#running-jobs-on-the-runner-machine
+        run: |
+          docker run \
+            -d \
+            --name user-service-test \
+            -e ENV_SERVER_PORT=$PORT \
+            -e ENV_DATABASE_PASSWORD=$DATABASE_PASSWORD \
+            -p 1234:1234 \
+            totocorpsoftwareinc/user-service:${{ needs.extract-service-tag.outputs.version }}
+          echo "status_code=$(curl -s -o /dev/null -w %{http_code} localhost:1234/v1/users)" >> $GITHUB_OUTPUT
+          echo "response_body=$(curl -s localhost:1234/v1/users)" >> $GITHUB_OUTPUT
+          docker stop user-service-test
+        id: test-results
+        env:
+          PORT: 1234
+          DATABASE_PASSWORD: manager_password
+      - name: Print test results
+        run: |
+          echo ${{ steps.test-results.outputs.status_code }}
+          echo ${{ steps.test-results.outputs.response_body }}
+      - name: Verify status code
+        run: |
+          if [[ ${{ steps.test-results.outputs.status_code }} != '200' ]]; then
+            echo "::error ::Expected http status code to be 200 but it was ${{ steps.test-results.outputs.status_code }}!"
+            exit 1
+          fi
+      - name: Verify response body
+        # https://stackoverflow.com/questions/58862864/github-actions-ci-conditional-regex
+        # https://stackoverflow.com/questions/4542732/how-do-i-negate-a-test-with-regular-expressions-in-a-bash-script
+        run: |
+          if ! [[ '${{ steps.test-results.outputs.response_body }}' =~ ^\{\"requestId\":\"[0-9a-f-]+\",\"status\":\"SUCCESS\",\"details\":\[\]\}$ ]]; then
+            echo "::error ::Expected http response to match expected syntax but it did not: ${{ steps.test-results.outputs.response_body }}!"
+            exit 1
+          fi
